import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "@/app/globals.css";
import Header from "@/components/header";
import Footer from "@/components/footer";
import CheckingAuth from "@/utils/checkingAuth";

const geistOutfit = Outfit({
  subsets: ["latin"],
});
export const metadata: Metadata = {
  title: "Name",
  description: "Generated by create next app",
};

export default async function AppointmentLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const Auth = await CheckingAuth();
  return (
    <html lang="en">
      <body
        className={`antialiased min-h-screen ${geistOutfit} dark:bg-gray-900`}
      >
        <Header userCookie={Auth} />
        {children}
        <Footer />
      </body>
    </html>
  );
}
