import Header from "@/components/header"
import { Metadata } from "next";
import { Outfit } from "next/font/google"
import "@/app/globals.css"
import { cookies } from "next/headers";
import FetchingCookies from "@/utils/auth";
import CheckingAuth from "@/utils/checkingAuth";
const geistOutfit = Outfit({
  subsets:["latin"],
  // variable:'--font-outfit'
 })
 export const metadata: Metadata = {
  title: "Doctor Appointment",
  description: "Generated by create next app",
};

export default async function AppointMentLayout(props:LayoutProps<"/">){
  const userAuthDoctorAppointment = await CheckingAuth();
    return (
        <html lang="en">
              <body
                // className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen`}
                className={`antialiased min-h-screen ${geistOutfit} dark:bg-gray-900 dark:text-white/90`}
              >
                <Header userCookie={userAuthDoctorAppointment}/>
                {props?.children}
              </body>
            </html>
    )
}